In [1]:
import pandas as pd
from sklearn import linear_model

import numpy as np
import matplotlib.pyplot as plt

In [253]:
path="C:/Users/Artem/Documents/goto hack/"
dfout = pd.read_excel(path + "qiwi_users_money_out_data.xlsx")
dfin = pd.read_excel(path + "qiwi_users_money_in_data.xlsx")
dfu = pd.read_excel(path + "qiwi_users_profile_data.xlsx")

In [3]:
dfout['type']='outcome'
dfin['type']='income'
dfinout=pd.concat([dfin,dfout])
df=pd.merge(dfinout,dfu,on='user_id')
df=df.fillna('Нет')
dfu=dfu.fillna('Нет')
df['tran_year'] = df.date_month.str.split('-').str.get(0).astype(int)
df['tran_month'] = df.date_month.str.split('-').str.get(1).astype(int)
df['graduated_ago'] = df['tran_year'] - df['graduation_year']

In [19]:
#df.to_csv('all_data.csv',index=None,sep=';')

In [4]:
df.head(1)

,category,date_month,txn_count,payment,user_id,type,sex,university,faculty,graduation_year,tran_year,tran_month,graduated_ago
0,QIWI,2014-02,1,70,2,income,Муж,ТвГТУ,Управления и социальных коммуникаций (Гуманита...,2016,2014,2,-2

In [5]:
university_list = dfu.university.unique()

In [150]:
pers_dic={}
sub_dfin = df[(df['type']=='income')&(df['graduation_year']==2017)&(df['tran_year']>2014)]
sub_dfout = df[(df['type']=='outcome')&(df['graduation_year']==2017)&(df['tran_year']>2014)]
for i in range(1,15113+1):
    sub_dic={}
    if i%3000==0:
        print(i)
    Nincome = len (sub_dfin[sub_dfin.user_id==i])
    Noutcome = len (sub_dfout[sub_dfout.user_id==i])
    meanincome = sub_dfin[sub_dfin.user_id==i].payment.mean()
    meanoutcome = sub_dfout[sub_dfout.user_id==i].payment.mean()
    
    sub_dic['user_id'] = i
    sub_dic['Nincome'] = Nincome
    sub_dic['Noutcome'] = Noutcome
    sub_dic['meanincome'] = meanincome
    sub_dic['meanoutcome'] = meanoutcome
    
    pers_dic[i] =  sub_dic
df_pers = pd.DataFrame(pers_dic)
df_pers=df_pers.transpose()
df_pers = df_pers.fillna(0)
#pers_dic

3000
6000
9000
12000
15000

In [338]:
df[(df['type']=='income')&(df['graduation_year']==2017)&(df['tran_year']>2014)]

,category,date_month,txn_count,payment,user_id,type,sex,university,faculty,graduation_year,tran_year,tran_month,graduated_ago
19,QIWI,2015-01,1,50,3,income,Нет,МГУ,Глобальных процессов,2017,2015,1,-2
20,QIWI,2015-02,1,90,3,income,Нет,МГУ,Глобальных процессов,2017,2015,2,-2
196,QIWI,2015-08,2,200,15,income,Муж,КубГАУ,Управления (Государственного и муниципального ...,2017,2015,8,-2
197,QIWI,2015-09,2,100,15,income,Муж,КубГАУ,Управления (Государственного и муниципального ...,2017,2015,9,-2
198,QIWI,2015-10,1,100,15,income,Муж,КубГАУ,Управления (Государственного и муниципального ...,2017,2015,10,-2
199,Форекс,2016-09,1,250,15,income,Муж,КубГАУ,Управления (Государственного и муниципального ...,2017,2016,9,-1
481,QIWI,2015-02,3,6000,40,income,Муж,РГУ им. Канта (бывш. КГУ),Институт социально-гуманитарных технологий и к...,2017,2015,2,-2
482,QIWI,2015-03,1,2000,40,income,Муж,РГУ им. Канта (бывш. КГУ),Институт социально-гуманитарных технологий и к...,2017,2015,3,-2
483,QIWI,2015-04,3,9000,40,income,Муж,РГУ им. Канта (бывш. КГУ),Институт социально-гуманитарных технологий и к...,2017,2015,4,-2
484,QIWI,2015-05,3,5200,40,income,Муж,РГУ им. Канта (бывш. КГУ),Институт социально-гуманитарных технологий и к...,2017,2015,5,-2
485,QIWI,2015-07,1,1000,40,income,Муж,РГУ им. Канта (бывш. КГУ),Институт социально-гуманитарных технологий и к...,2017,2015,7,-2
486,QIWI,2015-08,4,4000,40,income,Муж,РГУ им. Канта (бывш. КГУ),Институт социально-гуманитарных технологий и к...,2017,2015,8,-2
487,QIWI,2015-11,2,4500,40,income,Муж,РГУ им. Канта (бывш. КГУ),Институт социально-гуманитарных технологий и к...,2017,2015,11,-2
488,QIWI,2015-12,3,14000,40,income,Муж,РГУ им. Канта (бывш. КГУ),Институт социально-гуманитарных технологий и к...,2017,2015,12,-2
489,QIWI,2016-03,3,9100,40,income,Муж,РГУ им. Канта (бывш. КГУ),Институт социально-гуманитарных технологий и к...,2017,2016,3,-1
490,QIWI,2016-04,2,10000,40,income,Муж,РГУ им. Канта (бывш. КГУ),Институт социально-гуманитарных технологий и к...,2017,2016,4,-1
491,QIWI,2016-05,1,1000,40,income,Муж,РГУ им. Канта (бывш. КГУ),Институт социально-гуманитарных технологий и к...,2017,2016,5,-1
492,QIWI,2016-06,2,2000,40,income,Муж,РГУ им. Канта (бывш. КГУ),Институт социально-гуманитарных технологий и к...,2017,2016,6,-1
493,QIWI,2016-07,1,1500,40,income,Муж,РГУ им. Канта (бывш. КГУ),Институт социально-гуманитарных технологий и к...,2017,2016,7,-1
494,QIWI,2016-08,1,3000,40,income,Муж,РГУ им. Канта (бывш. КГУ),Институт социально-гуманитарных технологий и к...,2017,2016,8,-1
584,QIWI,2015-05,1,400,45,income,Нет,РГУ им. Канта (бывш. КГУ),Институт прикладной математики и информационны...,2017,2015,5,-2
585,QIWI,2015-06,1,400,45,income,Нет,РГУ им. Канта (бывш. КГУ),Институт прикладной математики и информационны...,2017,2015,6,-2
671,QIWI,2015-02,1,400,50,income,Муж,БГСХА,Институт ветеринарной медицины и биотехнологии,2017,2015,2,-2
672,QIWI,2015-03,3,1400,50,income,Муж,БГСХА,Институт ветеринарной медицины и биотехнологии,2017,2015,3,-2
673,QIWI,2015-04,1,200,50,income,Муж,БГСХА,Институт ветеринарной медицины и биотехнологии,2017,2015,4,-2
674,QIWI,2015-05,2,2300,50,income,Муж,БГСХА,Институт ветеринарной медицины и биотехнологии,2017,2015,5,-2
675,QIWI,2015-06,2,300,50,income,Муж,БГСХА,Институт ветеринарной медицины и биотехнологии,2017,2015,6,-2
676,QIWI,2015-08,1,2000,50,income,Муж,БГСХА,Институт ветеринарной медицины и биотехнологии,2017,2015,8,-2
677,QIWI,2015-10,5,2200,50,income,Муж,БГСХА,Институт ветеринарной медицины и биотехнологии,2017,2015,10,-2
678,QIWI,2015-11,4,800,50,income,Муж,БГСХА,Институт ветеринарной медицины и биотехнологии,2017,2015,11,-2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
287993,QIWI,2015-02,2,2000,15105,income,Муж,СПбГТИ (ТУ),Экономики и менеджмента,2017,2015,2,-2
287994,QIWI,2015-03,1,1000,15105,income,Муж,СПбГТИ (ТУ),Экономики и менеджмента,2017,2015,3,-2
287995,QIWI,2015-04,2,3000,15105,income,Муж,СПбГТИ (ТУ),Экономики и менеджмента,2017,2015,4,-2
287996,QIWI,2015-05,1,1100,15105,income,Муж,СПбГТИ (ТУ),Экономики и менеджмента,2017,2015,5,-2
287997,QIWI,2015-06,1,1000,15105,income,Муж,СПбГТИ (ТУ),Экономики и менеджмента,2017,2015,6,-2
287998,QIWI,2015-07,1,1000,15105,income,Муж,СПбГТИ (ТУ),Экономики и менеджмента,2017,2015,7,-2
287999,QIWI,2015-08,1,1000,15105,income,Муж,СПбГТИ (ТУ),Экономики и менеджмента,2017,2015,8,-2
288000,QIWI,2015-09,1,1000,15105,income,Муж,СПбГТИ (ТУ),Экономики и менеджмента,2017,2015,9,-2
288001,QIWI,2015-10,1,3000,15105,income,Муж,СПбГТИ (ТУ),Экономики и менеджмента,2017,2015,10,-2
288002,QIWI,2015-11,1,5000,15105,income,Муж,СПбГТИ (ТУ),Экономики и менеджмента,2017,2015,11,-2
288003,QIWI,2016-04,1,150,15105,income,Муж,СПбГТИ (ТУ),Экономики и менеджмента,2017,2016,4,-1
288004,Букмекеры,2015-11,1,100,15105,income,Муж,СПбГТИ (ТУ),Экономики и менеджмента,2017,2015,11,-2
288005,Терминалы и отделения партнеров QIWI,2015-12,2,800,15105,income,Муж,СПбГТИ (ТУ),Экономики и менеджмента,2017,2015,12,-2
288006,Терминалы и отделения партнеров QIWI,2016-01,1,800,15105,income,Муж,СПбГТИ (ТУ),Экономики и менеджмента,2017,2016,1,-1
288007,Терминалы и отделения партнеров QIWI,2016-02,3,1300,15105,income,Муж,СПбГТИ (ТУ),Экономики и менеджмента,2017,2016,2,-1
288008,Терминалы и отделения партнеров QIWI,2016-04,1,800,15105,income,Муж,СПбГТИ (ТУ),Экономики и менеджмента,2017,2016,4,-1
288009,Терминалы и отделения партнеров QIWI,2016-06,1,100,15105,income,Муж,СПбГТИ (ТУ),Экономики и менеджмента,2017,2016,6,-1
288010,Терминалы и отделения партнеров QIWI,2016-11,1,250,15105,income,Муж,СПбГТИ (ТУ),Экономики и менеджмента,2017,2016,11,-1
288059,QIWI,2015-02,1,1500,15106,income,Муж,НИ ИрГТУ (бывш. ИПИ),Институт недропользования,2017,2015,2,-2
288060,QIWI,2015-05,2,400,15106,income,Муж,НИ ИрГТУ (бывш. ИПИ),Институт недропользования,2017,2015,5,-2
288061,QIWI,2015-06,2,700,15106,income,Муж,НИ ИрГТУ (бывш. ИПИ),Институт недропользования,2017,2015,6,-2
288062,QIWI,2015-09,1,300,15106,income,Муж,НИ ИрГТУ (бывш. ИПИ),Институт недропользования,2017,2015,9,-2
288063,QIWI,2016-02,1,600,15106,income,Муж,НИ ИрГТУ (бывш. ИПИ),Институт недропользования,2017,2016,2,-1
288187,QIWI,2015-06,2,3200,15112,income,Муж,ГИТР,Кинотелеоператорского мастерства,2017,2015,6,-2
288188,QIWI,2015-08,1,2500,15112,income,Муж,ГИТР,Кинотелеоператорского мастерства,2017,2015,8,-2
288189,QIWI,2015-09,1,100,15112,income,Муж,ГИТР,Кинотелеоператорского мастерства,2017,2015,9,-2
288190,QIWI,2015-10,3,7000,15112,income,Муж,ГИТР,Кинотелеоператорского мастерства,2017,2015,10,-2
288191,QIWI,2015-11,2,7500,15112,income,Муж,ГИТР,Кинотелеоператорского мастерства,2017,2015,11,-2
288192,QIWI,2015-12,1,50,15112,income,Муж,ГИТР,Кинотелеоператорского мастерства,2017,2015,12,-2
288193,QIWI,2016-08,1,150,15112,income,Муж,ГИТР,Кинотелеоператорского мастерства,2017,2016,8,-1

In [7]:
df_pers.head()

   Nincome  Noutcome  meanincome  meanoutcome  user_id
1      0.0       4.0         0.0  1102.500000      1.0
2      5.0       6.0       464.0   388.333333      2.0
3      0.0       0.0         0.0     0.000000      3.0
4      0.0       0.0         0.0     0.000000      4.0
5      0.0       0.0         0.0     0.000000      5.0

In [270]:
un_dic={}
sub_dfin = df[(df['type']=='income')&(df['graduation_year']==2016)&(df['tran_year']<2016)]
sub_dfout = df[(df['type']=='outcome')&(df['graduation_year']==2016)&(df['tran_year']<2016)]

for university in university_list:
    sub_dic={}
    #if i%3000==0:
    #    print(i)
    Stud_number = len (df[ (df['university']==university )&(df['graduation_year']==2016 )].user_id.value_counts())
    if Stud_number!=0:
        Nincome = len (sub_dfin[sub_dfin.university==university]) / Stud_number
        Noutcome = len (sub_dfout[sub_dfout.university==university]) / Stud_number
        meanincome = sub_dfin[sub_dfin.university==university].payment.mean()
        meanoutcome = sub_dfout[sub_dfout.university==university].payment.mean()
        sub_dic['university'] = university
        sub_dic['Nincome'] = Nincome
        sub_dic['Noutcome'] = Noutcome
        sub_dic['meanincome'] = meanincome
        sub_dic['meanoutcome'] = meanoutcome
        sub_dic['number_of_stud'] = Stud_number
        
        un_dic[university] =  sub_dic


df_un = pd.DataFrame(un_dic)
df_un=df_un.transpose()
df_un = df_un.fillna(0)
#pers_dic
#df_un[df_un.number_of_stud>19]

In [380]:
umen_un = pd.read_excel(path + "unem.xlsx")
df_show = pd.merge(df_un,umen_un,on='university')
df_show[df_show['number_of_stud']>21].sort(columns = 'meanoutcome' ,ascending=False)

C:\Users\Artem\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  app.launch_new_instance()

,Nincome,Noutcome,meanincome,meanoutcome,number_of_stud,university,probability
19,3.500000,5.553571,2980.306122,1969.228296,56,СПбГУ,0.80
23,3.820000,7.640000,3317.591623,1779.554974,50,УГТУ-УПИ,0.80
15,4.227273,8.318182,2117.204301,1390.437158,22,ПНИПУ (бывш. ПГТУ),0.85
8,6.192308,9.346154,1762.857143,1301.646091,26,МГУ им. Огарева,0.80
7,6.089783,10.000000,1987.900356,1278.080495,323,МГУ,0.80
14,5.425532,10.276596,1930.705882,1193.664596,47,ННГУ им. Лобачевского,0.85
13,3.000000,7.241379,2501.149425,1160.095238,29,НИУ ВШЭ (ГУ-ВШЭ),0.80
16,8.000000,17.846154,2192.259615,1131.228448,26,РЭУ им. Г. В. Плеханова,0.80
18,2.333333,4.566667,1831.000000,1125.109489,30,СПбГПУ Политех,0.90
1,4.714286,9.821429,1804.621212,901.163636,28,ВлГУ им. А.Г. и Н.Г. Столетовых (ВлГУ и ВГГУ),0.80
12,4.681818,11.045455,2068.349515,899.465021,22,НГТУ им. Алексеева,0.90
24,6.281250,10.312500,1453.631841,809.060606,32,ЮУрГУ,0.70
10,6.965517,19.655172,1721.633663,776.175439,29,МФТИ (ГУ),0.95
3,3.111111,6.972222,1121.696429,764.302789,36,КФУ (бывш. КГУ им. Ульянова-Ленина),0.85

In [383]:
dfspec = pd.read_excel(path + "spec.xlsx")
df_plus_spec = pd.merge(dfspec,df,on='faculty')
df_plus_spec.head()
spec_list = ['тех','мат','общ','гум','мед']
prob_list = [0.8, 0.77,0.7,0.72,0.7857]
big_dic_spec = {}
for i in range(5):
    small_dic = {}
    people = len(sub_set.user_id.value_counts())
    sub_set = df_plus_spec[ (df_plus_spec.scpec==spec_list[i])&(df_plus_spec.graduation_year==2016)&(df_plus_spec['tran_year']<2016) ]
    #sub_set.user_id.unique
    Nincome = len(sub_set[sub_set['type']=='income'].payment)/people
    Noutcome = len(sub_set[sub_set['type']=='outcome'].payment)/people
    meanincome = sub_set[sub_set['type']=='income'].payment.mean()
    meanoutcome = sub_set[sub_set['type']=='outcome'].payment.mean()
    small_dic['Nincome'] = Nincome
    small_dic['Noutcome'] = Noutcome
    small_dic['meanincome'] = meanincome
    small_dic['meanoutcome'] = meanoutcome
    small_dic['number_of_stud'] = people   
    small_dic['prob'] = prob_list[i]   
    big_dic_spec[spec_list[i]] = small_dic
df_spec = pd.DataFrame(big_dic_spec).transpose()

In [411]:
df_spec.iloc[:,5]

гум    0.7200
мат    0.7700
мед    0.7857
общ    0.7000
тех    0.8000
Name: prob, dtype: float64

In [447]:
#код для регрессии
umen_un = pd.read_excel(path + "unem.xlsx")
df_X_train=pd.merge(df_un,umen_un,on='university')

df_X_train.meanincome=df_X_train.meanincome
df_X_train.meanoutcome=df_X_train.meanoutcome
df_pers_norm=df_pers.copy()
df_pers_norm.meanincome=df_pers.meanincome
df_pers_norm.meanoutcome=df_pers.meanoutcome

P_train =  np.concatenate(( df_X_train.probability.as_matrix(),df_spec.iloc[:,5].as_matrix()))
Y_train= np.log(P_train/(1- P_train)) 
X_train = np.concatenate((df_X_train.iloc[:,0:4].as_matrix(),df_spec.iloc[:,0:4].as_matrix()))
X_train[:,2] = X_train [:,2]
X_train[:,3] = X_train [:,3]
from sklearn import linear_model
from sklearn import preprocessing
reg = linear_model.Lasso(alpha = 0.015,fit_intercept=True,normalize=True)
reg.fit(X_train, Y_train)
#генерируем тестовую выборку
X_test = df_pers_norm.iloc[:,0:4].as_matrix()
X_test[:,2] = X_test[:,2]
X_test[:,3] = X_test [:,3]
pred_prob = np.exp(reg.predict(X_test))/(1+np.exp(reg.predict(X_test)))
df_pers['pred_prob'] = pred_prob
Itog = pd.merge(df_pers,dfu,on='user_id')
uni_rating={}
for university in university_list:
    uni_rating[university] = {'pred_prob':Itog[Itog['university']==university].pred_prob.mean()}
our_rating = pd.DataFrame(uni_rating).transpose()
our_rating[our_rating.pred_prob<0.86]
print ((reg.coef_))
print (df_pers.pred_prob.max() )
print ( df_pers.pred_prob.min() )
our_rating.pred_prob.min()
Itog[(Itog.pred_prob<0.7)&(Itog.Noutcome!=0)].head()
print (reg.get_params())

[ -0.00000000e+00  -0.00000000e+00  -0.00000000e+00  -7.12195421e-05]
0.833438217744
0.391882032309
{'max_iter': 1000, 'warm_start': False, 'random_state': None, 'fit_intercept': True, 'copy_X': True, 'normalize': True, 'tol': 0.0001, 'selection': 'cyclic', 'precompute': False, 'alpha': 0.015, 'positive': False}

array([ 1272.2826087 ,   901.16363636,   857.24409449,   764.30278884,
         775.56701031,  1792.53012048,  1229.04255319,  1278.08049536,
        1301.64609053,  1586.8134715 ,   776.1754386 ,  1667.69230769,
         899.46502058,  1160.0952381 ,  1193.66459627,  1390.43715847,
        1131.22844828,   592.83783784,  1125.10948905,  1969.22829582,
        2025.        ,  1160.94117647,   949.26108374,  1779.55497382,
         809.06060606,   343.        ,   373.        ,   106.        ,
         220.        ,    43.        ])

In [303]:
df_spec.iloc

In [364]:
#df_un[df_un.number_of_stud>20].sort(columns='meanincome',ascending=False)
len(df.user_id.unique())

15113

In [365]:
df.graduation_year.unique()

array([2016, 2017, 2018, 2015, 2014], dtype=int64)

In [336]:
dfu

,user_id,sex,university,faculty,graduation_year
0,1,Муж,ТвГТУ,Дополнительного профессионального образования,2016
1,2,Муж,ТвГТУ,Управления и социальных коммуникаций (Гуманита...,2016
2,3,NaN,МГУ,Глобальных процессов,2017
3,4,NaN,ЧелГУ,Управления,2018
4,5,NaN,ЮУрГУ,Факультет экономики и управления (до 2016 г.),2015
5,6,Муж,ЮУрГУ,"Институт спорта, туризма и сервиса",2016
6,7,NaN,ЮУрГУ,Архитектурно-строительный факультет (до 2016 г.),2015
7,8,Муж,ВлГУ им. А.Г. и Н.Г. Столетовых (ВлГУ и ВГГУ),Механико-технологический (ИИТ),2018
8,9,NaN,УГГУ (бывш. УГГГА),Институт сокращенной подготовки,2015
9,10,Муж,УГТУ-УПИ,Высшая школа экономики и менеджмента,2015
10,11,NaN,УрГПУ,Институт менеджмента и права (Институт кадрово...,2018
11,12,Муж,УрГПУ,Институт физической культуры,2014
12,13,NaN,КубГАУ,Прикладной информатики,2014
13,14,NaN,"СПбГЭУ (ранее ФИНЭК, ИНЖЭКОН, СПбГУСЭ)",Экономики и финансов,2016
14,15,Муж,КубГАУ,Управления (Государственного и муниципального ...,2017
15,16,NaN,МГА им. адмирала Ушакова (бывш. НВИМУ),"Институт морского транспортного менеджмента, э...",2018
16,17,Муж,ИМСИТ,NaN,2014
17,18,NaN,БГТУ им. Шухова,Химико-технологический институт (бывш. Институ...,2017
18,19,NaN,ИМСИТ,Информатики и вычислительной техники,2017
19,20,NaN,КубГАУ,Механизации,2017
20,21,NaN,КубГАУ,Ветеринарной медицины,2014
21,22,NaN,КубГТУ,"Экономики, управления и бизнеса",2017
22,23,NaN,КубГТУ,Институт компьютерных систем и информационной ...,2016
23,24,Муж,МГА им. адмирала Ушакова (бывш. НВИМУ),"Институт морского транспортного менеджмента, э...",2016
24,25,NaN,КубГАУ,Прикладной информатики,2016
25,26,NaN,ВГТУ (бывш. ВПИ),Информационных технологий и компьютерной безоп...,2014
26,27,NaN,Воронежский ГАСУ,NaN,2015
27,28,NaN,Воронежский ГАСУ,Заочного обучения,2015
28,29,NaN,"ВГУИТ (бывш. ВГТА, ВТИ)",Технологический,2016
29,30,NaN,СГТУ им. Ю.А. Гагарина (бывш. СПИ),Институт электронной техники и машиностроения,2015
...,...,...,...,...,...
15083,15084,NaN,РАНХиГС (СКАГС) при Президенте РФ,Управления,2015
15084,15085,NaN,РГЭУ РИНХ,Юридический,2017
15085,15086,NaN,ЮФУ (бывш. РГУ),Институт высоких технологий и пьезотехники,2015
15086,15087,NaN,ДГТУ (бывш. РИСХМ),"Автоматизации, мехатроники и управления",2017
15087,15088,NaN,ЮРГТУ (НПИ),Механический,2014
15088,15089,Муж,СКГМИ (ГТУ),Юридический,2018
15089,15090,NaN,КГУКИ,Экономики и управления,2015
15090,15091,NaN,НИУ ВШЭ (ГУ-ВШЭ),"Бизнеса и менеджмента (Бизнес-информатики, Лог...",2017
15091,15092,Муж,ГГНИ им. Миллионщикова,Автоматизации и прикладной информатики,2014
15092,15093,NaN,БашГУ,"Институт экономики, финансов и бизнеса",2017
15093,15094,Муж,УГГУ (бывш. УГГГА),Геологии и геофизики,2017
15094,15095,Муж,ЮУрГУ,"Компьютерных технологий, управления и радиоэле...",2018
15095,15096,Муж,ВолГАУ (бывш. ВГСХА),Биотехнологий и ветеринарной медицины,2018
15096,15097,Муж,МГУ,Физический,2016
15097,15098,NaN,ВГПУ,Социальной и коррекционной педагогики,2014
15098,15099,Муж,ГГНИ им. Миллионщикова,Автоматизации и прикладной информатики,2016
15099,15100,NaN,СПбГПУ Политех,Институт компьютерных наук и технологий (бывш....,2016
15100,15101,NaN,ННГУ им. Лобачевского,Механико-математический,2017
15101,15102,NaN,"ДВГУПС (бывш. ХабИИЖТ, ДВГАПС)",Институт экономики,2018
15102,15103,Муж,РГПУ им. Герцена,Институт педагогики и психологии (Психолого-пе...,2014
15103,15104,NaN,СПбГТИ (ТУ),Химии веществ и материалов (бывш. Химической т...,2018
15104,15105,Муж,СПбГТИ (ТУ),Экономики и менеджмента,2017
15105,15106,Муж,НИ ИрГТУ (бывш. ИПИ),Институт недропользования,2017
15106,15107,Муж,СГУГиТ (бывш. СГГА),Институт оптики и оптических технологий,2015
15107,15108,NaN,ЯрГУ им. П. Г. Демидова,Информатики и вычислительной техники,2016
15108,15109,Муж,МАИ,"Инженерно-экономический (ИНЖЭКИН МАИ, бывш. Эк...",2015
15109,15110,Муж,НИУ МЭИ (МЭИ ТУ),Институт тепловой и атомной энергетики,2016
15110,15111,NaN,ГИТР,Художественный,2015
15111,15112,Муж,ГИТР,Кинотелеоператорского мастерства,2017
15112,15113,NaN,МАТИ,"Институт менеджмента, экономики и социальных т...",2018